name: Build distribution 📦

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          pip install hatch --user

      - name: Run tests
        run: |
          python3 -m hatch run test

      - name: Run linting
        run: |
          python3 -m hatch run lint:all

      - name: Build a wheel and a source tarball
        run: |
          python3 -m hatch build
      
      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/*

